### ISSUE TITLE
Exception when unmounting before subscription websocket connection fully initialized

### ISSUE THREAD

**Issue by StefanSmith** [awslabs/aws-mobile-appsync-sdk-js#509]
**Do you want to request a *feature* or report a *bug*?**

*Bug*

**What is the current behavior?**

The following exception is thrown when a `graphql()`-enhanced React component is unmounted before the subscription websocket connection is fully initialized:

```
TypeError: Cannot read property 'subscriptionFailedCallback' of undefined

    at AppSyncRealTimeSubscriptionHandshakeLink.<anonymous> (*******/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js:307:112)
    at step (*******/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js:56:23)
    at Object.next (*******/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js:37:53)
    at fulfilled (*******/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js:28:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This issue is mentioned in the code base: https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/139a9775eebe6ac8a9df0b72975b522eeb2867cf/packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts#L299-L301

We are currently working around it using the following patch:

```
diff --git a/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js b/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js
index 6eb828e..03ee7e5 100644
--- a/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js
+++ b/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js
@@ -304,7 +304,12 @@ var AppSyncRealTimeSubscriptionHandshakeLink = /** @class */ (function (_super)
                         }
                         return [2 /*return*/];
                     case 5:
-                        _g = this.subscriptionObserverMap.get(subscriptionId), subscriptionFailedCallback = _g.subscriptionFailedCallback, subscriptionReadyCallback = _g.subscriptionReadyCallback;
+                        try {
+                            _g = this.subscriptionObserverMap.get(subscriptionId), subscriptionFailedCallback = _g.subscriptionFailedCallback, subscriptionReadyCallback = _g.subscriptionReadyCallback;
+                        } catch (e) {
+                            return [2 /*return*/];
+                        }
+
                         // This must be done before sending the message in order to be listening immediately
                         this.subscriptionObserverMap.set(subscriptionId, {
                             observer: observer,

```

**What is the expected behavior?**

Don't throw exception if unmounting before websocket connection is fully initialized.

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**

aws-appsync-subscription-link v2.0.1 with aws-appsync-react 3.0.2
Browser and nodejs (in tests)

**Comment by StefanSmith** [comment]
This is still an issue on v2.1.0

**Comment by dannywitters** [comment]
any updates here?

**Comment by rozzs74** [comment]
Hi, I am also encountering this issue  but this when I logout in the app. Any work arounds?
<img width="958" alt="Screen Shot 2020-08-07 at 1 14 04 pm" src="https://user-images.githubusercontent.com/14355779/89611477-ede05580-d8af-11ea-801f-2b6b1bb4c9da.png">

Cheers

**Comment by rubene** [comment]
Any updates on this? this is also affecting aws-amplify version 3.3.7

**Comment by houmark** [comment]
Still an issue. Fix should be trivial and simple (at least a try/catch).

**Comment by askurat** [comment]
I, too, am having this issue.

**Comment by MR-Neto** [comment]
Still having this issue after #616 is merged.

Found a workaround:
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/491#issuecomment-671469907

**Comment by ivajo26** [comment]
I, too, am having this issue.

**Comment by collinglass** [comment]
+1

**Comment by Zerquix18** [comment]
My Sentry is filled with this issue

**Comment by joekendal** [comment]
+1

**Comment by ShannonLCapper** [comment]
+1, would love to not have to see this hit in Sentry all the time

**Comment by joekendal** [comment]
> Found a workaround:
> [#491 (comment)](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/491#issuecomment-671469907)

The solution linked did not work for me. I found that this error was much less likely to occur once I switched to `subscribeToMore` instead of `useSubscription`. This way it waits for the component to mount before establishing the WebSocket connection. Additionally [this](https://github.com/apollographql/apollo-client/issues/6437#issuecomment-792306730) suggestion for wrapping `subscribeToMore` in `useLayoutEffect` as opposed to `useEffect` further eliminated the occurrence of this bug to the point where it doesn't seem to happen when switching routes quickly. On top of this you want to make sure that.

```ts
const { data, error, loading, subscribeToMore } = useQuery(gql(getPosts))


useLayoutEffect(() => {

    subscribeToMore({
        document: gql(onNewPost),

        variables: { user_id: user?.id },

        updateQuery: (prev: Post[], { subscriptionData }) => {
            if(subscriptionData.data) return prev;
            const newPost: Post = subscriptionData.data.onNewPost
            return Object.assign({}, prev, [newPost])
        }
    })

}, [subscribeToMore])
```

**Comment by david-mcafee** [comment]
@dexster - moving our conversation here, since your issue is related to #509, and not the `aws-sdk`. It looks like you are using an older version of the mobile AppSync SDK that supports Apollo V2. That does not include [this fix](https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/616) from @elorzafe that addresses this. One option would be to upgrade to Apollo V3, replace the AppSync client with the ApolloClient, and utilize our latest auth and subscription links. 

Example below:

```
import { Auth } from 'aws-amplify';
import { createAuthLink } from 'aws-appsync-auth-link';
import { createSubscriptionHandshakeLink } from 'aws-appsync-subscription-link';

import {
	ApolloLink,
	ApolloClient,
	ApolloProvider,
} from '@apollo/client';

import AppSyncConfig from './aws-exports';

const url = AppSyncConfig.aws_appsync_graphqlEndpoint;
const region = AppSyncConfig.aws_appsync_region;
const auth = {
	type: AppSyncConfig.aws_appsync_authenticationType,
	// <supply credentials here>
};

const link = ApolloLink.from([
	createAuthLink({ url, region, auth }),
	createSubscriptionHandshakeLink({ url, region, auth }),
]);

const client = new ApolloClient({
	link,
	// cache, if used
});

const WithProvider = () => (
	<ApolloProvider client={client}>
		<App />
	</ApolloProvider>
);

export default WithProvider;
```

Let me know if this is a possibility for you to try, or if you still run into the issue. Also, if you could send a code snippet where you are instantiating the subscription / what is generating the failure, that would help me further debug. Thank you!!

**Comment by dexster** [comment]
@david-mcafee Thanks for the feedback. Here's a code snippet. As other commenters above have mentioned, `subscribeToMore` is the culprit. If you comment it out the error goes away. 

How would the code below look like using apollo client?

```
import AWSAppSyncClient from 'aws-appsync';

testAppSync() {
        const client = new AWSAppSyncClient({
            url: ...,
            region: ...,
            auth: {
                type: ...,
                credentials: ...
            }
        });

        client.hydrated().then(client => {
            const query = client.watchQuery({
                query: gql(` query List...`),
                fetchPolicy: 'network-only'
            });

            query.subscribe(({data}) => {
                console.log('TEST APPSYNC: ', data);
            });

            query.subscribeToMore<any>({
                document: gql(`subscription OnCreate...`),
                updateQuery: (prev, {
                    subscriptionData: {
                        data: {
                            onCreate: page
                        }
                    }
                }) => {
                   // do something with data
                }
            });
        })
    }
```

**Comment by david-mcafee** [comment]
@dexster - happy to help! I'll send you some code examples from my testing apps tomorrow morning. Can you tell me what client framework you're using this in? I have examples in React, React Native, and Node, so perhaps I can share samples that fit directly with what you're working with. Thanks!

**Comment by dexster** [comment]
I probably should have mentioned that earlier. I'm using Angular 12

**Comment by david-mcafee** [comment]
@dexster I don't have any Angular examples at the moment, sorry! But here are the possible ways to resolve this issue.

1. I see you are already using Amplify, you could use this exclusively, and not use the AppSync SDK altogether. You would no longer be able to use Apollo as the GraphQL client, though. You can see the [Getting Started](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js/) guide for more info on that. You have two options here - the API, or DataStore.

2. Continue using the version of the AppSync SDK you are using. Can you tell me your use-case for using `subscribeToMore`? Perhaps the first thing you could do, with your current implementation and current version, is try something more similar to what is below:

```
const query = gql(`
	query listTodo {
		listTodos {
			items {
				id
				name
				description
			}
			nextToken
		}
	}
`);

const subquery = gql(`
	subscription OnCreateTodo {
		onCreateTodo {
			id
			name
			description
		}
	}
`);

client.hydrated().then(function (client) {
		client
			.query({ query })
			.then(function logData(data) {
				console.log('results of query: ', data);
			})
			.catch(console.error);

		const observable = client.subscribe({ query: subquery });

		const realtimeResults = function realtimeResults(data) {
			console.log('realtime data: ', data);
		};

		observable.subscribe({
			next: realtimeResults,
			complete: console.log,
			error: console.log,
		});
	});
```

3.  Upgrade the AppSync SDK to pull in the changes that fix the race condition on unmount, and use Apollo V3 (similar to the stripped down example I have below):
```
import React, { useEffect, useState } from 'react';
import gql from 'graphql-tag';
import { graphql, compose } from 'react-apollo';
import { graphqlMutation } from 'aws-appsync-react';
import { buildSubscription } from 'aws-appsync';

const listTodos = gql`
	query listTodo {
		listTodos {
			items {
				id
				name
				description
			}
			nextToken
		}
	}
`;

const TodoSubscription = gql`
	subscription OnCreateTodo {
		onCreateTodo {
			id
			name
			description
		}
	}
`;

const App = ({ todos, data, createTodo, deleteTodo }: any) => {

	useEffect(() => {
		data?.subscribeToMore(buildSubscription(TodoSubscription, listTodos));
	}, []);

	// Add Todo, render, etc
};

export default compose(
	graphql(listTodos, {
		options: {
			fetchPolicy: 'cache-and-network',
		},
		props: (props: any) => ({
			todos: props.data.listTodos
				? props.data.listTodos.items : [],
			data: props.data,
		}),
	}),
	graphqlMutation(CreateTodo, listTodos, 'Todo'),
	graphqlMutation(DeleteTodo, listTodos, 'Todo')
)(App);

```

**Comment by david-mcafee** [comment]
> Hi, I am also encountering this issue but this time after I logout in the app. Any work arounds?
> <img alt="Screen Shot 2020-08-07 at 1 14 04 pm" width="958" src="https://user-images.githubusercontent.com/14355779/89611477-ede05580-d8af-11ea-801f-2b6b1bb4c9da.png">
> 
> Cheers

@rozzs74 - are you calling `unsubscribe` on the observable? This may be your issue.

**Comment by dexster** [comment]
@david-mcafee 

1. I looked at using Amplify a while back. It would involve a large rewrite including the db to cater for the delta sync requirements of DataStore.
2.   I'm using subscribeToMore to check and process query updates as per this doc - https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query
3. I have got this working now with Apollo client using the packages you recommended: 
```
import { createAuthLink } from 'aws-appsync-auth-link';
import { createSubscriptionHandshakeLink } from 'aws-appsync-subscription-link';

import {
	ApolloLink,
	ApolloClient,
	ApolloProvider,
} from '@apollo/client';
```
My subscribeToMore is being triggered.
 
But, it is only working when I use the auth type `AMAZON_COGNITO_USER_POOLS` when creating my client

When I try creating a client using `AWS_IAM` for auth I get this error when the subscribeToMore  code loads:
message: "Connection failed: {\"errors\":[{\"errorType\":\"BadRequestException\",\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method....

This exact same IAM auth code works on my prod site using the old AwsAppSyncClient so I don't think it's a permissions or credentials issue. 

If we can get this sorted then I can document the complete working solution for the other participants in this issue

**Comment by david-mcafee** [comment]
@dexster - we are aware of the [IAM issue](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/619), and I have [a PR out now](https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/671) that will resolve these IAM issues. We are currently testing these changes. Once we verify that no other auth scenarios are affected by this PR, we'll merge it, and this will be fixed.

**Comment by dexster** [comment]
@david-mcafee  Awesome! Thanks. Eagerly awaiting the npm publish

**Comment by noobling** [comment]
I am still seeing this error after updating.. 

Please advise, this has been a real pain
![image](https://user-images.githubusercontent.com/23206864/133776207-5e66d85f-5992-47cd-a740-e047c1cce4c0.png)

**Comment by joekendal** [comment]
@noobling Same, I've given up and just gone with polling interval as recommended by the Apollo team. Unfortunately AppSync Subscriptions just aren't ready for customers as:

1. There is no way to put it behind CloudFront and have the signature still work using this SDK.
2. The subscriptionFailedCallback issue is a problem without a fix even in 2021.

It's a shame that Amazon doesn't place AppSync SDK as a higher priority as Amplify is not suitable for every project.

**Comment by dexster** [comment]
@david-mcafee When will this be published?

**Comment by david-mcafee** [comment]
@dexster, @noobling, and @joekendal - we have 2 other fixes that we are currently working on that will go out with our next release. I'll update this ticket when the change has been pushed to npm. Thanks!

**Comment by david-mcafee** [comment]
@joekendal, @noobling, and @ryancrunchi - can you explain what Apollo versions you are using, and perhaps give examples of how you are setting up the client? We recently updated our README to make this more clear, but open to suggestions if it's still ambiguous.

If you are using Apollo V3 (and this is the suggested approach), then you will NOT want to use `aws-appsync` to create your client. Instead, you'll want to use the latest versions of the subscription and / or auth links, and follow the configuration listed here: https://github.com/awslabs/aws-mobile-appsync-sdk-js#using-authorization-and-subscription-links-with-apollo-client-v3-no-offline-support

However, if you are using Apollo V2, you can still use the `aws-appsync` package, but you'll need to use the minor versions that we recently published. For Apollo V2, that's version `2.2.6` for the subscription link (see the `apolloV2` tag listed under "Versions": https://www.npmjs.com/package/aws-appsync-subscription-link, and version `2.0.7` for the auth link, also listed under the `apolloV2` tag: https://www.npmjs.com/package/aws-appsync-auth-link).

If you have followed the above and are still running into an issue, please let me know and we can re-open this issue.

**Comment by Mootook** [comment]
@david-mcafee I am still facing this issue having recently upgraded our appsync dependencies.
```js
// package.json
"@apollo/client": "^v3.4.16",
"aws-amplify": "^4.3.4",
"aws-appsync-auth-link": "^3.0.7",
"aws-appsync-subscription-link": "^3.0.9",

// init.js
const getLinks = () => {
  const authLink = createAuthLink(ApolloManager.APP_SYNC_CONFIG)
  const subscriptionLink = createSubscriptionHandshakeLink(
    ApolloManager.APP_SYNC_CONFIG
  )
  return from([authLink, subscriptionLink])
}

const initClient = () => {
  const client = new ApolloClient({
    link: getLinks(),
    cache: new InMemoryCache(),
    connectToDevTools: true,
    ...ApolloManager.APP_SYNC_OPTIONS
  })
  ApolloManager.instance = client
  return client
}
```

**Comment by ryancrunchi** [comment]
On our side we have cognito and api key links. Some of our operations are used with cognito others with api key.

```javascript
// package.json
"@apollo/client": "^v3.4.16",
"aws-amplify": "^4.3.4",
"aws-appsync-auth-link": "^3.0.7",
"aws-appsync-subscription-link": "^3.0.9"

// start
import { createAuthLink } from 'aws-appsync-auth-link'
import { createSubscriptionHandshakeLink } from 'aws-appsync-subscription-link'

const apiKeyLink = ApolloLink.from([
  errorLink,
  createAuthLink(apiKeyConfig),
  createSubscriptionHandshakeLink(apiKeyConfig),
])

const cognitoLink = ApolloLink.from([
  errorLink,
  createAuthLink(config) as any,
  createSubscriptionHandshakeLink(config),
])

const client = new ApolloClient({
  link: // ... custom conditional link, cognitoLink or apiKeyLink ...,
  cache: new InMemoryCache({
    addTypename: false,
  }),
})
```

**Comment by florian42** [comment]
Hi, we are experiencing this type of error too. Our setup is as described here https://github.com/awslabs/aws-mobile-appsync-sdk-js#using-authorization-and-subscription-links-with-apollo-client-v3-no-offline-support and the versions we use are also:

```
"aws-amplify": "^4.3.4",
"aws-appsync": "^4.1.4",
"aws-appsync-subscription-link": "^3.0.9",
```

In our case, we want to look for updates when opening the page for a specific entity/item. Hence, we couple the subscription to our query:

```
function useGetSpecificEntity(variables?: SpecificEntityFragment | null) {

    const {loading, data, error, subscribeToMore, refetch} = useQuery(SpecificEntityDocument, {
        variables,
        skip: !variables,
        fetchPolicy: 'cache-and-network',
    });

    useEffect(() => {
        if (!variables?.id) {
            return noop;
        }

        const unsubscribe = subscribeToMore({
            document: NotifyOnChangesToSpecificEntity,
            variables: {id: variables.id, path: SubscriptionPath.Root},
            updateQuery: (prev) => {
                void refetch();
                return prev;
            },
        });

        return () => {
            unsubscribe();
        };
    }, [variables, refetch, subscribeToMore]);
}
```
Note that to stop the subscription, we invoke unsubscribe as part of the useEffect cleanup.
We can provoke this type error when reloading the page. Now in the source for [realtime-subscription-handshake-link.ts#L323](https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/f5c6e1a1be0bfa43fce5615deefe3a8777374268/packages/aws-appsync-subscription-link/src/realtime-subscription-handshake-link.ts#L323) I can see that `this.subscriptionObserverMap.get(subscriptionId);` is probably undefined and hence `subscriptionFailedCallback ` is undefined too.

Now my question is, why can `this.subscriptionObserverMap.get(subscriptionId)` be undefined? Are we doing something wrong, or is there a bug in the library?

**Comment by nihcal** [comment]
Still facing this problem, can someone advice?
![image](https://user-images.githubusercontent.com/62795930/150068272-b1a909fa-1264-4c4d-a467-7381fd42f98b.png)
![image](https://user-images.githubusercontent.com/62795930/150068344-208d396b-4875-445b-b485-69e4fc325653.png)
![image](https://user-images.githubusercontent.com/62795930/150068555-f9e2bc45-bbcd-4295-a8ee-45c100ec5438.png)

**Comment by david-mcafee** [comment]
@Mootook - can you provide additional details on what the issue is that you are seeing? Some additional details could help us understand what the issue is (i.e. what type of auth are you using, are you running into an issue regarding subscribing / unsubscribing). Could provide a snippet of the client code where the error is happening, along with the error itself? 

@ryancrunchi / @nihcal  - could you provide a snippet of the client code where the error is happening? Also, have you tried instantiating the client at the entry point of your app, instead of in the useEffect hook? A debugger in this hook could help you figure out if you're attempting to instantiate the client multiple times (i.e. on each render).

A @florian42 pointed out, this error often correlates to creating and stopping multiple subscriptions in quick succession, which can be avoided by not attempting to create a subscription on each render.

**Comment by david-mcafee** [comment]
Update: Amplify JS has a solution for this (i.e. using a timeout before closing the subscription). I'll port this over to the AppSync SDK which should prevent this from breaking if a user attempts rapid subscription changes on mount / unmount.

**Comment by david-mcafee** [comment]
@Mootook, @ryancrunchi, and @nihcal - the changes have been merged for both the master branch (i.e. the subscription link), and the apolloV2 branch (the AppSync client). If you could pull these changes (we'll be doing a release tomorrow, 2/8), I think you should be in good shape! :)

**Comment by adamduren** [comment]
@david-mcafee I have not seen a release on `aws-appsync-subscription-link`. It's currently still at `3.0.9`, any update on this?

**Comment by david-mcafee** [comment]
> @david-mcafee I have not seen a release on `aws-appsync-subscription-link`. It's currently still at `3.0.9`, any update on this?

@adamduren - we are planning to do a release this week. I'll update this ticket when we have released it. Thanks!

**Comment by david-mcafee** [comment]
@adamduren - we just released the latest version of the AppSync SDK on npm, and this fix is included. Please reach out if you have further questions, thanks!

**Comment by ryancrunchi** [comment]
Sorry to bump this again, but I still have this issue with version 3.0.11
I will try to create a reproductible sandbox

**Comment by alan-cooney** [comment]
Likewise still seeing this with 3.0.11 and @apollo/client 3.6.6

**Comment by pehel** [comment]
I am having the same issue in nextjs.

**Comment by stallev** [comment]
Hello @david-mcafee 
I'm getting an error
![image](https://user-images.githubusercontent.com/22907070/190382601-cfde2700-e406-4265-b0f1-ee34c2a7340b.png)
![image](https://user-images.githubusercontent.com/22907070/190384763-c0fd963b-b909-40b0-aa6a-a97eee9079fe.png)
![image](https://user-images.githubusercontent.com/22907070/190384962-f26f26c4-f97c-4027-888b-2eebab1b7324.png)

`"@aws-amplify/auth": "4.4.3",
        "@aws-amplify/ui-react": "1.2.20",
        "amazon-cognito-identity-js": "5.2.0",
        "amplify": "0.0.11",
        "aws-amplify": "4.3.13",
        "aws-appsync": "4.1.2",`

I read what you write at https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/509 but didn't find a solution for my problem.
I can repro it by switching between NextJS pages multiple times.

Could you point out the reason for this. If packages need to be upgraded, please specify to which version.
Could you send me some code examples?

Thanks a lot!

**Comment by dylan-westbury** [comment]
I was getting this error for a Tab within a Tab Navigator for react native (not lazy loaded), so I assume the component is mounting too fast leading to the error.

I solved for now using skip and setTimeout

```
const Component = () => {
  const [ init, setInit ] = useState(false);

  const { data: senderMessageData } = useSubscription(
    gql(SENDER_MESSAGE_SUBSCRIPTION),
    {
      skip: !userId || !init,
      variables: {
        sender: userId
      },
      onData: options => console.log('onData', options)
    }
  )

  useEffect(() => {
    setTimeout(() => {
      setInit(true);
    }, 300)
  }, [])
}
```

**Comment by radAragon** [comment]
Still seeing this with
```
"aws-appsync": "4.1.9",
"graphql": "15.8.0",
```

**Comment by JKazarian** [comment]
@david-mcafee have there been any updates to resolve this? The issue has been going on for two years.

**Comment by heanfig** [comment]
I am having the same issue in nextjs. two years with the same issue

**Comment by shawngustaw** [comment]
@JKazarian @radAragon could you test/verify this PR to fix this? https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/747. To build I had to add `types: []` to the `tsconfig.json` but then you can run `yarn prepare && yarn pack` and then `yarn add ../path/to/package.tar.gz` the file that gets created from `yarn pack`.

**Comment by nch3ng** [comment]
the issue still happening, it's been years.

**Comment by ivadenis** [comment]
have the same issue
